### ISSUE TITLE
[Suggestion] Ability to customize background opacity and avatar coloring

### ISSUE THREAD

**Issue by TheRenegadist** [jaw-sh/stream-nexus#2]
May already be planned but having the ability to set background opacity or remove the background entirely would be a nice feature.

Also having the ability to control colors around avatars would be nice, I like the idea of colors for each website but also having colors for moderators, subs, etc would make it confusing if someone outside of the system trying to figure out what goes to what. Alternatively it may be cool to display a small website icon somewhere that shows what website they're chatting on and then rely on colors to display moderators only. If the scope of the project permits maybe a control panel would be the best solution for all of this.

**Comment by jaw-sh** [comment]
the css can be changed while the webserver is running. it does not cache and an f5 applies the changes.

**Comment by TheRenegadist** [comment]
I don't know too much about css, can you provide an example of code for disabling the grey background entirely and just displaying the website colors and none of the sub, moderator, etc ones?

Edit: Admittedly I have no idea what I'm doing, I guess I make a good test subject for the average dumb streamer trying to use this. Maybe a tutorial for what to do should be put into readme or pinned somewhere? I'll probably be streaming this weekend so it would be nice to test this for you guys.

**Comment by ghost** [comment]
Maybe allow setting colour codes in the env file or something? Doesn't seem hard to implement.

Sorry for the accidental close. I'm dumb.

**Comment by TheRenegadist** [comment]
Oh, confirmed retard brain. I just found the style.css which is what I assume you're talking about. Looks like background stuff is there so maybe as mentioned including a file for setting RGB based colors for websites/functionality and maybe the option for website icons?

**Comment by ghost** [comment]
It's the same sort of idea as the css, but I would want to do it in a way where people don't need to potentially break a css file. Just simple hex codes.

In addition, maybe an advanced option for a user-style.css for more powerful overrides.

**Comment by TheRenegadist** [comment]
Since I already botched this issue thread with gross incompetence I did want to ask if Twitch support will also eventually be added since you mentioned Kick was in the works.

**Comment by ghost** [comment]
No worries, I see no incompetence here (except my close).

I don't see why not. Twitch, for better or worse, is synonymous with live streaming. I'll take a look at it.
