### ISSUE TITLE
Add chat feed integration tests

### ISSUE THREAD

**Issue by iCantSneed** [jaw-sh/stream-nexus#32]
Since chats like to break from time to time, rather than getting surprised by it during livestreams, integration tests should be created and run nightly to catch problems before they occur live on stream.

**Comment by cohlexyz** [comment]
It'd be useful but considering how the fetching works it would be quite the pain in the ass to setup. You'd need like a headless browser that has Tampermonkey and the user scripts installed as well as a live stream for all supported platforms that is active during the test. Also Kick has very aggressive Cloudflare turnstile checks that would make it even harder. Unless someone can think of a reliable way to do this the tests themselves would probably break just as often as the thing they're supposed to test.

**Comment by jaw-sh** [comment]
Integration test??? these are all guerilla scripts designed specifically to run in your browser and hijack/wrap javascript events to get around the grueling anti-bot stuff specifically designed to break scraping bots. there's no way to deal with this automatically. I just have to painfully test everything continuously and remember to fix it after streams. these platforms are designed to break systems like this.

**Comment by jaw-sh** [comment]
the issue with rumble btw is XSS origins. the script has to import scripts from 3rd party sites so if it's not in browser cache it just breaks. no clue what bullshit is happening with odysee or kick though.

**Comment by jaw-sh** [comment]
Closed with #34. This suggestion is unfeasible. If you want to propose a way to actually accomplish this, go ahead and reopen it.
