### ISSUE TITLE
Some small issues with polls and super-chat styling

### ISSUE THREAD

**Issue by cohlexyz** [jaw-sh/stream-nexus#6]
Some things I noticed during the last stream
- [x] Usernames in super-chats from paid rumble subscribers are hard to read:
![image](https://github.com/jaw-sh/stream-nexus/assets/142505474/21df73bc-6ab7-42c2-b2fc-dedfc682fecd)
- [x] Same with links:
![image](https://github.com/jaw-sh/stream-nexus/assets/142505474/8cd74935-fa0e-48b6-9db8-44b9d27160c0)
- [x] `!endpoll` makes the poll disappear. It should probably just stop accepting votes, mark the option that won and then maybe after a timeout of 15 seconds or so it should actually fade out
- [x] At the end of the stream the poll timed out after two minutes while you were looking for the outro song, idk if you want that changed

Fixing the readability is a bit hard since the color of the super-chat changes so the colors would have to be dependent on that.

I also saw that some users in chat couldn't figure out how to vote and used `!vote1`, `!1` or just the number. I could make the counting a bit more flexible so it accounts for really dense people who can't follow simple instructions. Someone also suggested that the messages people send for voting shouldn't show up in the chat overlay so they don't clutter it up.

Lastly something I thought about that might be useful is the web server hosting a separate dashboard page that aggregates all donations during a stream. That way you don't have to go to the different sites to read them at the end and you'll also not lose them if you refresh rumble. The dashboard could also offer some other options like starting/ending polls or re-submitting a super-chat in case it gets lost when refreshing the overlay in obs. That dashboard could also be added as dock to obs since obs studio allows you to dock any website you want via the menu bar option `Docks > Custom Browser Docks`. If that's something that you'd find useful I can try and make a basic version of it.

**Comment by jaw-sh** [comment]
I'm intending to do all of that, it won't be much work. I can make multiple overlay pages on the applicaton.
