### ISSUE TITLE
Migrating to WebExtensions

### ISSUE THREAD

**Issue by ghost** [jaw-sh/stream-nexus#8]
I moved all of the websockets chat stuff to a simple WebExtension format for better unity. It works nicely in testing on Firefox and Chromium. This has the added benefit of allowing us to move the generic chat message functions to a single loader script.

Since this would cause a major structural change, I put the first version of the extension in a repo [here](https://github.com/f-sneed/sneed-relay) for now.

Cheers

**Comment by jaw-sh** [comment]
I want to have the WebSockets handled by Rust. 

What I wanted with reorganizing the JS was making it so that there was some sort of node-based system for webpacking extensions so that development was less copy+paste and applying changes between site instances was not so much a pain.

**Comment by ghost** [comment]
I'm not sure I follow. It's still the same idea as the current JS stuff. It just doesn't need separate userscripts. This is for relaying messages from the browser.
